version: "3.7"
services:
  node:
    image: my_super_app
    restart: always
    environment:
      MYSQL_DATABASE_USERNAME: user
      MYSQL_DATABASE_PASSWORD: toor
      MYSQL_DATABASE_NAME: my_db

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER : user
      MYSQL_PASSWORD : toor

